### ISSUE TITLE
I was wondering if you had the chance to work with UDP tproxy code in go?

### ISSUE THREAD

**Issue by elico** [andrew-d/demux#1]
I was wondering if you had the chance to work with UDP tproxy code in go?
I have used your code and managed to write a tproxy service for TCP but I have no examples at all for a UDP tproxy implementation in golang.

Thanks

**Comment by andrew-d** [comment]
Sorry, but I have only used TCP tproxy - never UDP.

**Comment by andrew-d** [comment]
If you do manage to get UDP working, please feel free to leave a comment, though - it would be interesting if someone is able to make it work!

**Comment by elico** [comment]
I must just mention that I have found some tproxy example at:
https://github.com/hkwi/https_tproxy/blob/master/main.go
Which looks a bit nicer since it uses the regular "net.Listen" command.(not tested it)
